### ISSUE TITLE
example测试报错

### ISSUE THREAD

**Issue by Leadrive** [foxitsoftware/flutter-foxitpdf#2]
flutter+android, sdk是最新的6.2
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.17763.1637], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)

````javascript
E/flutter ( 2891): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel flutter_foxitpdf)    
E/flutter ( 2891): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160:7)                                                                                 
E/flutter ( 2891): <asynchronous suspension>                                                                                                                                                      
E/flutter ( 2891): #1      FlutterFoxitpdf.platformVersion (package:flutter_foxitpdf_example/flutter_foxitpdf.dart:11:28)                                                                         
E/flutter ( 2891): <asynchronous suspension>                                                                                                                                                      
E/flutter ( 2891): #2      _MyAppState.initPlatformState (package:flutter_foxitpdf_example/main.dart:41:25)                                                                                       
E/flutter ( 2891): <asynchronous suspension>                                                                                                                                                      
E/flutter ( 2891):                                                                                                                                                                                
E/flutter ( 2891): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel flutter_foxitpdf)            
E/flutter ( 2891): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160:7)                                                                                 
E/flutter ( 2891): <asynchronous suspension>                                                                                                                                                      
E/flutter ( 2891): #1      FlutterFoxitpdf.initialize (package:flutter_foxitpdf_example/flutter_foxitpdf.dart:16:23)                                                                              
E/flutter ( 2891): <asynchronous suspension>                                                                                                                                                      
E/flutter ( 2891): #2      _MyAppState.init (package:flutter_foxitpdf_example/main.dart:73:15)                                                                                                    
E/flutter ( 2891): <asynchronous suspension>                                                                                                                                                      
E/flutter ( 2891):                                                                                                                                                                                
E/flutter ( 2891): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method openDocument on channel flutter_foxitpdf)          
E/flutter ( 2891): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160:7)                                                                                 
E/flutter ( 2891): <asynchronous suspension>                                                                                                                                                      
````

**Comment by yongliang-huang** [comment]
这个错误出现的原因是Plugin的方法没有找到，也可能是Plugin本身就没有注册成功，可以试试flutter clean一下，再次 flutter run/build

**Comment by Leadrive** [comment]
是否是试用序列号的原因？按下载的SDK里提供的填写的

````javascript
  String _platformVersion = '6.2';
  int _error = -1;

  String _sn = 'AAF1VK0AHQs7rFENl/hzZWDzmzMLwF+Neg2aMWEMpkjb9guK7bYnFA==';
  String _key =
      'ezJvjl3GtGh397voL2Xkb3l6wo2NvErcymNKusezbU+yjsFWDqO4wL1F6WcuW67rnspRArTR6SCkc8VbkYb85msr7UyxMyyvy253IwdFWHCZYxm3w/nEa+Og5BVv2pWsUB2uPnLHajmXvQ40tIcL50pf5iR6JZggVS81HLAravQs7WOvWyme0yCOk1GBi0D5T5YVzrSZIFOMyIvUoA6vqFKgYdMUCksompl/fvIWyTiIO7vhBO/er0OD7VLf44Ts/tjubhVBxwMKvJl6I735zn7meklO4KZtugmUi23cv9s7eiV5tz8KpOIyOEZct4PmWQoJFxfRNw2Pe2cj/imm5viYLlkc6EL+fR3CGfV1OZs+0NjgkH25wYnHoxJMCcJ5Fn5SIOn4sK280n8fmgiDQyEpaMA+oO7N84YdshPsY8ghk05VV2tKGw53zM3o6tVh6tySNoJA4J5bXu0Je7ws3gUWy9Fnwf+SNv3uIqID969zeen/UhEe5UbBlUWp2+K4SlNmPgy48l00kpmTHtatl8z5r5FCgjBhEMlGFL5NpX3U2ab/NH5nvTsbA17DNFhBFnwQrlSQvGtqS6QPDY/gEztKSYjSbL9ze95aYgSmVs45IPIZ7jwO4e6d2yd715jmD79GKo8Y710QlMVdhiOQpNMcdF+L30PQnciIIVs2M1dKqlACy+r1F0qQXAGjeNsnKe6DbcEMv1gs9ZklNTUGIjvHL2XkI+27Ih/lTkS4gQNmDcQo/QpvTuv0FpXxvuOTzzcNBQGFRkOm7kGdFC9Khc+tje9oW5m3iJFLtGSzlqaoiPnuUmtBjadF6TCwgJoq0VSz3wR0TQYHsZHEStpq85dzYeYXlbpDC1YBYFBKw+132MdNJ2wS1VuXWybj1UcgAfugj/E2Lo1G4M4hGlBLQHC3TiPZiG3Ig3bUubNyCcYllciCLShO8eUIngcMI16dY3M6OFtWmEf7/xIJjOHxAzrJ5ugQ9ERhieedaiQK/Rx7Q2uuiia7eUpJ4a6oFmKjSz67wJfZJb+LwjuUXiwBVFfqGK2sO7q7gHs1vmuwvQLoHD+PxmV/byFKS1EoBQYjUvT+GM8sNha84i40Wx52odgG18c5zSnZNWSSVsv0opE3oSr6hr6TLlCcidlYUiDN/xRdYoHsJB+dgIB/54y5JJg0EBKgpIFuUm8sw5KDl0Ou4qanp7ux5x/yGvBdVYJ6IsvdZGSInznEZ/g/omyiXcnwnxwZHIJfbSWmRzZOZhlMJ/g3LOZ2ByM=';
  // String _path = '/mnt/sdcard/FoxitSDK/complete_pdf_viewer_guide_android.pdf';
  String _path = '/storage/emulated/0/Pictures/a.pdf';
````

**Comment by Leadrive** [comment]
可以对比下pdftron，没有序列号，也能测试，只是有水印。
